import java.util.*;

public class guessTheNumber { 
    
    Scanner input = new Scanner(System.in); 
    Random rand = new Random();

    public int takeUserInput(){ 
        System.out.print("Enter your guess: ");
        int guess = input.nextInt(); 
        System.out.println();
        return guess;
    } 
    int comp;
    int guessCount;  

    public void compare(int guess, int comp){ 
        
        if(guess == comp){
            System.out.println("Congratulations! That is the correct number!"); 
            guessCount++; 
            System.out.println("Your no. of guesses: "+guessCount+"\n");
        }
        else if (guess > comp) {
            System.out.println("Your guess is more than the actual number! \nTry Again!\n"); 
            guessCount++;             
        } 
        else if(guess < comp) {
            System.out.println("Your guess is less than the actual number! \nTry Again!\n"); 
            guessCount++; 
        }
    }
    

    public static void main(String[] args) {
        System.out.println("Welcome to the game!");
        System.out.println("Here, you have to guess the number (0-100) generated by the computer. The one with the least no. of guesses, wins!");

        Scanner input = new Scanner(System.in); 
        Random rand = new Random(); 

        guessTheNumber player1 = new guessTheNumber(); 

        player1.comp = rand.nextInt(101); 
        int comp1 = player1.comp; 
        player1.guessCount = 0; 
        int guess; 

        do { 
            guess = player1.takeUserInput(); 
            player1.compare(guess, comp1);
        } while (guess != comp1); 
        input.close();
    }

}